name: fds_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=22.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2022.12.7
  - cachecontrol=0.12.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - cleo=2.0.1
  - click=8.0.4
  - cmake=3.22.1
  - contourpy=1.0.5
  - crashtest=0.4.1
  - cryptography=39.0.1
  - cvxpy=1.3.1
  - cvxpy-base=1.3.1
  - cycler=0.11.0
  - distlib=0.3.6
  - dulwich=0.21.3
  - ecos=2.0.12
  - expat=2.4.9
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - html5lib=1.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - jaraco.classes=3.2.1
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.17.3
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - kneed=0.7.0
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libqdldl=0.1.5
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightgbm=3.3.5
  - llvm-openmp=14.0.6
  - lockfile=0.12.2
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - missingno=0.4.2
  - more-itertools=8.12.0
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.4
  - nltk=3.7
  - openssl=1.1.1t
  - osqp=0.6.2.post0
  - packaging=23.0
  - patsy=0.5.3
  - pexpect=4.8.0
  - pillow=9.4.0
  - pip=23.0.1
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - poetry=1.4.0
  - poetry-core=1.5.1
  - poetry-plugin-export=1.3.0
  - pooch=1.4.0
  - ptyprocess=0.7.0
  - pybind11=2.10.1
  - pybind11-global=2.10.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-installer=0.6.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2022.7
  - qdldl-python=0.1.5.post2
  - rapidfuzz=2.13.7
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-toolbelt=0.9.1
  - rhash=1.4.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - scs=3.2.3
  - shellingham=1.5.0
  - six=1.16.0
  - sqlite=3.41.2
  - statsmodels=0.13.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tqdm=4.65.0
  - trove-classifiers=2023.3.9
  - tzdata=2023c
  - urllib3=1.26.15
  - virtualenv=20.17.1
  - webencodings=0.5.1
  - wheel=0.38.4
  - wordcloud=1.8.2.2
  - xattr=0.10.1
  - xz=5.2.10
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiodns==3.0.0
      - aiofiles==22.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - aiosqlite==0.18.0
      - alpha-vantage==2.3.1
      - altair==4.2.2
      - ansiwrap==0.8.4
      - anyio==3.6.2
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - ascii-magic==1.6
      - astor==0.8.1
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - babel==2.12.1
      - backcall==0.2.0
      - backoff==2.2.1
      - base58==2.1.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blinker==1.6
      - bs4==0.0.1
      - bt==0.2.9
      - cachetools==5.3.0
      - ccxt==2.9.16
      - charset-normalizer==2.1.1
      - comm==0.1.3
      - commonmark==0.9.1
      - convertdate==2.4.0
      - cssselect==1.2.0
      - cython==0.29.34
      - dateparser==1.1.8
      - datetime==5.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - degiro-connector==2.0.21
      - detecta==0.0.5
      - dnspython==2.3.0
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - exchange-calendars==4.2.6
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - feedparser==6.0.10
      - ffn==0.3.6
      - financedatabase==2.1.0
      - finnhub-python==2.4.17
      - finviz==1.4.6
      - finvizfinance==0.14.5
      - flake8==6.0.0
      - formulaic==0.3.4
      - fqdn==1.5.1
      - fred==3.1
      - fredapi==0.4.3
      - frozendict==2.3.6
      - frozenlist==1.3.3
      - fundamentalanalysis==0.2.14
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - grpcio==1.53.0
      - hijri-converter==2.2.4
      - holidays==0.14.2
      - inflection==0.5.1
      - interface-meta==1.3.0
      - intrinio-sdk==6.23.1
      - ipyflex==0.2.6
      - ipykernel==6.22.0
      - ipympl==0.8.4
      - ipython==8.5.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - iso8601==0.1.16
      - isodate==0.6.1
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - json5==0.9.11
      - jsonpointer==2.3
      - jupyter-client==7.4.1
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==1.23.6
      - jupyter-server-fileid==0.8.0
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.3
      - jupyterlab==3.6.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.0
      - jupyterlab-widgets==3.0.7
      - korean-lunar-calendar==0.3.1
      - linearmodels==4.27
      - loguru==0.6.0
      - lxml==4.9.2
      - markupsafe==2.1.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mistune==2.0.5
      - mplfinance==0.12.9b7
      - mstarpy==0.0.4
      - multidict==6.0.4
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - nbclassic==0.5.5
      - nbclient==0.7.3
      - nbconvert==7.3.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - notebook==6.5.4
      - notebook-shim==0.2.2
      - numpy==1.23.4
      - oandapyv20==0.6.3
      - oauthlib==3.2.2
      - onetimepass==1.0.1
      - openbb==2.5.1
      - openpyxl==3.1.2
      - pandas==1.5.3
      - pandas-datareader==0.10.0
      - pandas-market-calendars==3.2
      - pandas-ta==0.3.14b0
      - pandocfilters==1.5.0
      - papermill==2.4.0
      - parso==0.8.3
      - pickleshare==0.7.5
      - plotly==5.14.1
      - praw==7.7.0
      - prawcore==2.3.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - property-cached==1.6.4
      - protobuf==3.20.1
      - psaw==0.0.12
      - psutil==5.9.3
      - pure-eval==0.2.2
      - pyally==1.1.2
      - pyarrow==11.0.0
      - pycares==4.3.0
      - pycodestyle==2.10.0
      - pycoingecko==2.3.0
      - pycryptodome==3.17
      - pydantic==1.10.7
      - pydeck==0.8.0
      - pyflakes==3.0.1
      - pygments==2.14.0
      - pyhdfe==0.1.2
      - pyluach==2.2.0
      - pymeeus==0.5.12
      - pympler==1.0.1
      - pyobjc-core==9.0.1
      - pyobjc-framework-cocoa==9.0.1
      - pyotp==2.8.0
      - pyprind==2.11.3
      - pyrsistent==0.18.1
      - pythclient==0.1.4
      - python-binance==1.0.17
      - python-coinmarketcap==0.2
      - python-dotenv==0.19.2
      - python-i18n==0.3.9
      - python-json-logger==2.0.7
      - pytrends==4.9.1
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - pyzmq==25.0.2
      - quandl==3.7.0
      - rdflib==6.3.2
      - requests-futures==1.0.0
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==12.6.0
      - robin-stocks==2.1.0
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - screeninfo==0.6.7
      - seaborn==0.11.2
      - send2trash==1.8.0
      - setuptools==65.4.1
      - setuptools-scm==6.4.2
      - sgmllib3k==1.0.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - sparqlwrapper==2.0.0
      - squarify==0.4.3
      - stack-data==0.6.2
      - stocksera==0.1.21
      - streamlit==1.21.0
      - tabulate==0.9.0
      - tenacity==7.0.0
      - terminado==0.17.1
      - textwrap3==0.9.2
      - thepassiveinvestor==1.2.1
      - tinycss2==1.2.1
      - tokenterminal==1.0.1
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.2
      - tradingview-ta==3.3.0
      - traitlets==5.9.0
      - tweepy==4.13.0
      - typing-extensions==4.5.0
      - tzlocal==4.3
      - ujson==5.7.0
      - update-checker==0.18.0
      - uri-template==1.2.0
      - user-agent==0.1.10
      - vadersentiment==3.3.2
      - validators==0.20.0
      - valinvest==0.0.2
      - voila==0.4.0
      - watchdog==2.3.1
      - wcwidth==0.2.6
      - webcolors==1.13
      - websocket-client==1.5.1
      - websockets==11.0.1
      - widgetsnbextension==4.0.7
      - wrapt==1.15.0
      - y-py==0.5.9
      - yahooquery==2.3.1
      - yarl==1.8.2
      - yfinance==0.2.14
      - ypy-websocket==0.8.2
      - zope-interface==6.0
